apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k1dgmz1jp-java-springboot
  janus-idp.io/tekton: k1dgmz1jp-java-springboot
  backstage.io/kubernetes-id: k1dgmz1jp-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k1dgmz1jp-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
